#!/bin/bash

input_file="$1"

if [ ! -f "$input_file" ]; then
    echo "Usage: $0 <file>"
    echo "Please provide a valid input file."
    exit 1
fi

while read -r number; do
    if [[ $number =~ ^[0-9]+$ && $number -gt 1 ]]; then
        factors=""
        for ((i = 2; i <= number / 2; i++)); do
            if ((number % i == 0)); then
                factor1=$i
                factor2=$((number / i))
                factors="$factor1*$factor2"
                break
            fi
        done

        if [ -n "$factors" ]; then
            echo "$number=$factors"
        else
            echo "$number"  # Number cannot be factored
        fi
    else
        echo "Invalid number: $number"
    fi
done < "$input_file"
